#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1
# ---------------------------------------------------------------------------------------------------------
#  / ___| | | | | | |            / \   _ __      / \ \      / / ___|   / ___| |   |_ _| |_   _|__   ___ | |
# | |   | | | | | | |  _____    / _ \ | '_ \    / _ \ \ /\ / /\___ \  | |   | |    | |    | |/ _ \ / _ \| |
# | |___| |_| | |_| | |_____|  / ___ \| | | |  / ___ \ V  V /  ___) | | |___| |___ | |    | | (_) | (_) | |
#  \____|\___/ \___/          /_/   \_\_| |_| /_/   \_\_/\_/  |____/   \____|_____|___|   |_|\___/ \___/|_|
# ---------------------------------------------------------------------------------------------------------
#                               | |/ / ___|| | | | |  _ \ _   _| | ___  ___| | | |
#                               | ' /\___ \| |_| | | |_) | | | | |/ _ \/ __| | | |
#                               | . \ ___) |  _  | |  _ <| |_| | |  __/\__ \_|_|_|
#                               |_|\_\____/|_| |_| |_| \_\\__,_|_|\___||___(_|_|_)
# ---------------------------------------------------------------------------------------------------------
#                                / ___| __ ___      _| | __ |  _ \ _   _| | ___  ___ 
#                               | |  _ / _` \ \ /\ / / |/ / | |_) | | | | |/ _ \/ __|
#                               | |_| | (_| |\ V  V /|   <  |  _ <| |_| | |  __/\__ \
#                                \____|\__,_| \_/\_/ |_|\_\ |_| \_\\__,_|_|\___||___/
# ---------------------------------------------------------------------------------------------------------
# README.md Start
# CUU - An AWS CLI Wrapper
# M <pre>
usage(){
     print ""
     print "Usage: cuu [-h][-a][-u][-p][-t][-d][-D][-j][-F][-B][-E][-R][-Z][-i][-c]"
     print "      -a  operand:  cli profile name      (from .aws/config)"
     print "      -u  operand:  username"
     print "      -p  operand:  password    (default may be set in ~/.cuu.txt)"
     print "      -t  operand:  thing name  (specify a resource or object name)"
     print "      -T  operand:  time window in hours (to specify now-T to now)"
     print "      -h  display usage"
     print "      -d  limits abbreviations"
     print "      -D  Specify a document\file to upload (e.g. a policy document)"
     print "      -j  use long datetime fields"
     print "      -F  force mode, do not confirm any command"
     print "      -B  show full user names"
     print "      -E  show event names"
     print "      -R  show raw records in output"
     print "      -Z  output iso time"
     print "      -i  interactive mode ('q' to quit)"
     print "      -c  command:"
     print "          Optional :ULIST: may specify a user, a list of users, or the special keyword ALLUSERS"
     print "          Optional :PLIST: may specify a profile, a list of profiles, or the special keyword ALLPROFILES"
     print "          ----------------------------------------------------------------------------------------------"
     print "User Commands"
     print "     lu     listusers                -a :PLIST:    List users" 
     print "            deleteuser               -a -u         Delete the user"
     print "     du     describeusers            -a :PLIST:    List users and their attached groups and policies" 
     print "            createuser               -a -u -p      Creates with no privledges"
     print "            createadminuser          -a -u -p      Creates a user with Administor Access"
     print "            createreadonlyuser       -a -u -p      Creates a user with Read Only"
     print "     scram  scrampassword            -a -u         Assignis the user an unknown (scrammed) password"
     print "     cp     changepassword           -a -u -p      Changes a user password"
     print "                                                   For commands above, User will change password"
     print "                                                   after first login.  Password may be set in ~/.cuu.txt"
     print "Access Key Commands"
     print "     lak    listaccesskeys           -a -u         List the users access keys"
     print "     rak    replaceaccesskeys        -a -u         Deletes all keys for user, Creates a single new key"
     print "     cak    createaccesskey          -a -u         Creates an access key for the user"
     print "     dak    deleteaccesskeys         -a -u         Deletes all the users access keys"
     print "Policy Commands"
     print "            createpolicy             -a -t         Create new policy (-t) with policydoc.json template"
     print "            deletepolicy             -a -t         Delete policy by name (-t)"
     print "     lp     listallpolicies          -a            Lists all defined policies"
     print "     lpl    listlocalpoliciesl       -a            Lists local (user managed) policies"
     print "     lpa    listawspolicies          -a            Lists aws policies"
     print "     upp    updatepolicy             -a -t -D      Update local policy name (-t) with policy doc (-D, use file://)"
     print "            attachpolicyset          -a -u         Attach policy ARNs listed in file policyset.txt to user (-u)"
     print "            removepolicyset          -a -u         Removes policy ARNs listed in policyset.txt to user (-u)"
     print "     gap    getallpolicies           -a <-t regex> Get all policy docs defined for this profile"
     print "     glp    getlocalpolicies         -a <-t regex> Get all local policy docs defined for this profile"
     print "                                                   Use regex for a specific policy"
     print "            listuserpolicies         -a -u"
     print "            detachuserpolicies       -a -u"
     print "            attachpolicytouser       -a -u -t      Specify the policy arn (-t)"
     print "Group Commands"
     print "     lg     listgroups               -a            List all groups defined" 
     print "            listusergroups           -a -u         Lists groups associated with user"
     print "            addusertogroup           -a -u -t      Add user to a group (-t)"
     print "            removeuserfromallgroups  -a -u         Remove the user from attach attached groups"
     print "EC2 Commands"
     print "            ec2                      -a            List instances and securitygroups"
     print "            ec2-sg                   -a            Security groups detail listing"
     print "            ec2-sgsum                -a            Security groups summary listing (incl. empty SGs)"
     print "CloudTrail Commands"
     print "     ca     cloudtrail-active        -a -T         Lists active users in time window"
     print "     cu     cloudtrail-user          -a -u -T      Lists user activity in time window"
     print "     cz     cloudtrail-allusers      -a -T         Runs cloudtrail-users for all users"
     print "     cw     cloudtrail-watch         -T            Runs cloudtrail-users for each profile in PROFILELIST"
     print "                                                   on the WATCHUSER in ~/.cuu.txt"
     print "                                                   -T specifies time window in hour"

     print "Specific Policy Commands"
     print "            iamuserchangepassword-add    -a -u :ULIST: Adds Policy"
     print "            iamuserchangepassword-remove -a -u :ULIST: Removes Policy"
     print "Other"
     print "            time                     -T            Print time window"
     print ""
     print "Note: Abbreviations are applied to output fields to limit line length"
     print "            -d will limit abbreviations"
}
# M </pre>
# README.md End
commandABBREVIATIONS() {
	case "$COMMAND" in
            DUMENU)                COMMAND="USERMENU" ;;
            UM)                    COMMAND="USERMENU" ;;
            DUM)                   COMMAND="USERMENU" ;;
            CAK)                   COMMAND="CREATEACCESSKEYS" ;;
            RAK)                   COMMAND="REPLACEACCESSKEYS" ;;
            LAK)                   COMMAND="LISTACCESSKEYS" ;;
            DAK)                   COMMAND="DELETEACCESSKEYS" ;;
            GLP)                   COMMAND="GETLOCALPOLICIES" ;;
            GAP)                   COMMAND="GETALLPOLICIES" ;;
            LAP)                   COMMAND="LISTALLPOLICIES" ;;
            LLP)                   COMMAND="LISTLOCALPOLICIES" ;;
            LAWSP)                 COMMAND="LISTAWSPOLICIES" ;;
            CP)                    COMMAND="CHANGEPASSWORD" ;;
            CA)                    COMMAND="CLOUDTRAIL-ACTIVE" ;;
            CU)                    COMMAND="CLOUDTRAIL-USER" ;;
            CZ)                    COMMAND="CLOUDTRAIL-USER"
                                   USERNAME="ALL"
                                   ;;
            CW)                    COMMAND="CLOUDTRAIL-WATCH" ;;
            LU)                    COMMAND="LISTUSERS" ;;
            DU)                    COMMAND="DESCRIBEUSERS" ;;
            DESCRIBEUSER)          COMMAND="DESCRIBEUSERS" ;;
            LG)                    COMMAND="LISTGROUPS" ;;
            LR)                    COMMAND="LISTROLES" ;;
            SCRAM)                 COMMAND="SCRAMPASSWORD" ;;
	esac
}
# ---------------------------------------------------------------------------------------------------------
# MACROS
# ---------------------------------------------------------------------------------------------------------
window() {
     print "WINDOW START TIME  "$ISOAGO"  "$AGO
     print "WINDOW END TIME    "$ISOANON"  "$ANON
}
createACCESSKEY() {
     assertACCOUNTandUSERNAME
     aws --profile $ACCOUNT --output text iam create-access-key --user-name $USERNAME > $Tmp
     cat $Tmp | gawk -v A=$ACCOUNT -v U=$USERNAME '@include "cuu.awk"; { print configrecord($0,A,U,A); }'
}
createUSER() {
     assertACCOUNTandUSERNAMEandPASSWORD
     aws --profile $ACCOUNT iam create-user --user-name $USERNAME
     aws --profile $ACCOUNT iam create-login-profile --user-name $USERNAME --password $PASSWORD  --password-reset-required
     aws --profile $ACCOUNT iam attach-user-policy --user-name $USERNAME --policy-arn arn:aws:iam::aws:policy/IAMUserChangePassword
}
deleteUSER() {
     assertACCOUNTandUSERNAME
     aws --profile $ACCOUNT iam delete-login-profile --user-name $USERNAME 
     aws --profile $ACCOUNT iam delete-user --user-name $USERNAME 
}
wipeUSER() {
     assertACCOUNTandUSERNAME
     wipePOLICIES
     wipeGROUPS
     wipeACCESSKEYS
}
wipePOLICIES() {
     assertACCOUNTandUSERNAME
     LISTPOLICIES=`aws --profile $ACCOUNT iam list-attached-user-policies --user-name $USERNAME --query "AttachedPolicies[*].[PolicyArn]" --output text`
     for ITEM in $LISTPOLICIES; do
          aws --profile $ACCOUNT iam detach-user-policy --user-name $USERNAME --policy-arn $ITEM 
     done
     LISTPOLICIES=""
 }
wipeGROUPS() {
     assertACCOUNTandUSERNAME
     GROUPLIST=`aws --profile $ACCOUNT iam list-groups-for-user --user-name $USERNAME --query "Groups[*].[GroupName]" --output text`
     confirm
     for ITEM in $GROUPLIST; do
          aws --profile $ACCOUNT iam remove-user-from-group --user-name $USERNAME --group-name $ITEM 
     done
     GROUPLIST=""
}
wipeACCESSKEYS() {
     assertACCOUNTandUSERNAME
     ACCESSKEYLIST=`aws --profile $ACCOUNT iam list-access-keys --user-name $USERNAME  --query "AccessKeyMetadata[*].[AccessKeyId]" --output text`
     for ITEM in $ACCESSKEYLIST; do
          aws --profile $ACCOUNT iam delete-access-key --user-name $USERNAME --access-key-id $ITEM
     done
     ACCESSKEYLIST=""
}
# ---------------------------------------------------------------------------------------------------------
buildUSERLIST() {
          USERLIST=""
          if [ "$USERNAME" == "" ] ; then
              USERLIST=`aws --profile $1 iam list-users --query "Users[*].[UserName]" --output text`
          else
              USERLIST=$USERNAME
          fi
}
groupREMOVE() {
               aws --profile $ACCOUNT iam remove-user-from-group --user-name $USERNAME --group-name $1
}
optionalGROUPADD() {
          if [ "$THING" != "" ] ; then
                aws --profile $ACCOUNT iam add-user-to-group --group-name $THING  --user-name $USERNAME
          fi
}
groupADD() {
               aws --profile $ACCOUNT iam add-user-to-group      --user-name $USERNAME --group-name $1
}
groupsetREMOVE() {
               THISSET=`cat groupset.txt | egrep -v "(^#)|(^$)" | egrep arn[:]aws[:]iam`
               confirmset
               for ITEM in $THISSET; do
                    groupREMOVE $ITEM
               done
               THISSET=""
}
groupsetATTACH() {
               THISSET=`cat groupset.txt | egrep -v "(^#)|(^$)" | egrep arn[:]aws[:]iam`
               confirmset
               for ITEM in $THISSET; do
                    groupADD $ITEM
               done
               THISSET=""
}
policysetREMOVE() {
               THISSET=`cat policyset.txt | egrep -v "(^#)|(^$)" | egrep arn[:]aws[:]iam`
               confirmset
               for ITEM in $THISSET; do
                    policyREMOVE $ITEM
               done
               THISSET=""
}
policysetATTACH() {
               THISSET=`cat policyset.txt | egrep -v "(^#)|(^$)" | egrep arn[:]aws[:]iam`
               confirmset
               for ITEM in $THISSET; do
                    policyATTACH $ITEM
               done
               THISSET=""
}

policyREMOVE() {
               assertACCOUNTandUSERNAME
               LIST=$USERNAME
               for USER in $LIST; do
                    print $USER $1
                    aws --profile $ACCOUNT iam detach-user-policy --policy-arn $1 --user-name $USER
               done
               LIST=""
}
policyATTACH() {
               assertACCOUNTandUSERNAME
               LIST=$USERNAME
               for USER in $LIST; do
                    print $USER $1
                    aws --profile $ACCOUNT iam attach-user-policy --policy-arn $1 --user-name $USER
               done
               LIST=""
}

clean() {
    rm -rf $Tmp
    rm -rf ./cuu.out
    rm -rf ./cuureport.txt
}
awsnull() {
    NOTHING=0;
}
awsdbg() {
     printf "DBGOUT:   aws %s %s %s %s %s %s %s %s %s %s %s %s\n" $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12
}
assertfile() {
    if [ -a $1 ] ; then
         NOTHING=0
    else
         print "File "$1" Not Found"
         exit 1
    fi
}
asserte() {
    print "Checking: "$1
    if [ "$1" == "" ] ; then
         print $2
         exit 1
    fi
}
assert() {
    if [ "$1" == "" ] ; then
         print $2
         exit 1
    fi
}
assertACCOUNTandUSERNAME() {
     assert "$ACCOUNT" "Profile not specified"
     assert "$USERNAME" "User not specified"
}
assertACCOUNTandUSERNAMEandPASSWORD() {
     assert "$ACCOUNT"  "Profile not specified"
     assert "$USERNAME" "Username not specified"
     assert "$PASSWORD" "Password not specified"
}
assertACCOUNTandUSERNAMEandTHING() {
     assert "$ACCOUNT"  "Profile not specified"
     assert "$USERNAME" "Username not specified"
     assert "$THING"    $1" not specified"
}
assertACCOUNTandTHING() {
     assert "$ACCOUNT"  "Profile not specified"
     assert "$THING"    $1" not specified"
}
antiassert() {
    if [ "$1" != "" ] ; then
         print $2
         exit 1
    fi
}
confirmset() {
     print ""
     for ITEM in $THISSET; do
          print "   "$ITEM
     done
     confirm
}
confirmprompt() {
     print "   "$1
     confirm
}
confirm() {
     if [ "$FORCE" != "yes" ] ; then
          print -n "   For "$ACCOUNT":  Enter '10111' to confirm >> "
          read STRIN
          if [ "$STRIN" != "10111" ] ; then
               print "   Exiting - No Match"
               exit 1
          fi
     fi
}
typeset -u COMMAND
COMMAND=""
USERNAME=""
ACCOUNT=""
CREATEUSER=""
THING=""
COUNT=""
ACCTNUMBER=""
IN=""
OUT=""
FORCE=""
LOOP="no"
GROUPREMOVE="" 
POLICYADD="" 
REGION="us-east-1"
RAN=`tr -cd \#_[:alnum:] < /dev/urandom |  fold -w 18 | head -1 |gawk '{print $0 "!!"}'`
PASSWORD=`gawk -v w=PASSWORD -F= '{b="";gsub(re,b,$1);gsub(re,b,$2);if ($1==w) {print $2;exit;}}' ~/.cuu.txt`
WATCHUSER=`gawk -v w=WATCHUSER -F= '{b="";gsub(re,b,$1);gsub(re,b,$2);if ($1==w) {print $2;exit;}}' ~/.cuu.txt`
WATCHPROFILE=`gawk -v w=WATCHPROFILE -F= '{b="";gsub(re,b,$1);gsub(re,b,$2);if ($1==w) {print $2;exit;}}' ~/.cuu.txt`
PROFILELIST=`gawk -v w=PROFILELIST -F= '{b="";gsub(re,b,$1);gsub(re,b,$2);if ($1==w) {print $2;exit;}}' ~/.cuu.txt`
POLICYLIST=`gawk -v  w=POLICYLIST -F= '{b="";gsub(re,b,$1);gsub(re,b,$2);if ($1==w) {print $2;exit;}}' ~/.cuu.txt`
GROUPREMOVE=`gawk -v w=GROUPREMOVE -F= '{b="";gsub(re,b,$1);gsub(re,b,$2);if ($1==w) {print $2;exit;}}' ~/.cuu.txt`
POLICYADD=`gawk -v   w=POLICYADD -F= '{b="";gsub(re,b,$1);gsub(re,b,$2);if ($1==w) {print $2;exit;}}' ~/.cuu.txt`
TIMEFACTOR=`gawk -v  w=TIMEFACTOR -F= '{b="";gsub(re,b,$1);gsub(re,b,$2);if ($1==w) {print $2;exit;}}' ~/.cuu.txt`
DETAILFLAG=""
SHOWRAW="no" 
ISOTIME="no" 
BIGNAMES="no" 
BIGEVENTS="no" 

while getopts "jr:Ff:D:dn:c:Ru:a:p:t:ihbZBET:" arg
do
	case $arg in
            B) BIGNAMES="yes" ;;
            E) BIGEVENTS="yes" ;;
            Z) ISOTIME="yes" ;;
            r) REGION=$OPTARG  ;;
            F) FORCE="yes" ;;
            f) FILE=$OPTARG ;;
            i) LOOP="yes" ;;
            d) DETAIL="yes"; DETAILFLAG=" -d " ;;
            D) DOCUMENT=$OPTARG ;;
            n) COUNT=$OPTARG ;;
            T) TIMEFACTOR=$OPTARG ;;
            c) COMMAND=$OPTARG ;;
            u) USERNAME=$OPTARG
               if [ "$USERNAME" == "ALLUSERS" ] ; then
                  assert "$ACCOUNT"  "Profile not specified"
                  USERNAME=`aws --profile $ACCOUNT iam list-users --query "Users[*].[UserName]" --output text`
                  print "" 
                  print "   You are operating on all the users in the account"
                  print "" 
                  echo $USERNAME
                  print "" 
                  confirm
                  print "" 
               fi
               ;;
            R) SHOWRAW="yes" ;;
            p) PASSWORD=$OPTARG ;;
            t) THING=$OPTARG ;;
	    h) usage; exit 0 ;;
            a) ACCOUNT=$OPTARG
               if [ "$ACCOUNT" == "ALL" ] ; then
                   ACCOUNT=$PROFILELIST
               fi
               if [ "$ACCOUNT" == "ALLACCOUNTS" ] ; then
                   ACCOUNT=$PROFILELIST
               fi
               if [ "$ACCOUNT" == "LIST" ] ; then
                   ACCOUNT=$PROFILELIST
               fi
               ;;
	    *) exit 0 ;;
	esac
done
shift $(($OPTIND - 1))


if [ $# -eq 1 ] ; then
     if [ "$COMMAND" == "" ] ; then
          COMMAND=$1
     fi
fi

while [[ 0 -eq 0 ]];do

commandABBREVIATIONS

if [ "$TIMEFACTOR" == "" ] ; then
     TIMEFACTOR=24
fi
ISOAGO=`gawk -v T=$TIMEFACTOR '@include "cuu.awk"; BEGIN { print isoyesterhour(T);}'`
ISOANON=`gawk '@include "cuu.awk"; BEGIN { print isonow();}'`
AGO=`gawk  -v T=$ISOAGO  '@include "cuu.awk"; BEGIN { print isotolocal(T, "%m/%d/%Y %I:%M:%S%p");}'`
ANON=`gawk -v T=$ISOANON '@include "cuu.awk"; BEGIN { print isotolocal(T, "%m/%d/%Y %I:%M:%S%p");}'`
# -----------------------------------------------------------------------------------------------------------------------
# Notes
# https://aws.amazon.com/blogs/security/a-simple-way-to-export-your-iam-settings/
# aws --profile ECD3 iam get-account-authorization-details 
#   aws --profile ECD3 iam list-policies
#   aws --profile ECD3 iam list-policies
#   aws --profile ECD3 iam list-policies --scope Local
#   sz = "aws --profile " A " iam delete-access-key --user-name " U " --access-key-id  " $2
#   sz = "aws --profile " A " iam list-policy-versions --policy-arn " $2
#   aws --profile $ACCOUNT -output json iam create-policy-version --policy-arn $T --policy-document file://$FILE --set-as-default
#   aws --profile $ACCOUNT iam attach-user-policy --policy-arn arn:aws:iam::aws:policy/ReadOnlyAccess         --user-name $USERNAME
#   aws --profile $ACCOUNT iam attach-user-policy --policy-arn arn:aws:iam::aws:policy/CloudWatchFullAccess   --user-name $USERNAME
#   aws --profile $ACCOUNT iam attach-user-policy --policy-arn arn:aws:iam::aws:policy/AWSCodeCommitPowerUser --user-name $USERNAME
# arn:aws:iam::aws:policy/AWSCodeCommitPowerUser
# -----------------------------------------------------------------------------------------------------------------------

if [ "$COMMAND" == "TEST" ] ; then
#                       assertfile cuureport.txt
#                     assert "$ACCOUNT"  "Profile not specified"
#                     awsnull --profile $ACCOUNT iam create-user --user-name $USERNAME
#                     awsnull --profile $ACCOUNT iam create-login-profile --user-name $USERNAME --password $PASSWORD  --password-reset-required
#                     awsnull --profile $ACCOUNT iam attach-user-policy --policy-arn arn:aws:iam::aws:policy/$sz --user-name $USERNAME
#                     LIST=`aws --profile $ACCOUNT iam list-users --query "Users[*].[UserName]" --output text`
                     LIST=`cat arns`
                     for ITEM in $LIST; do
                         print $ITEM
                     done
NOTHING=0
fi

if [ "$COMMAND" == "PUBLISH" ] ; then
     assertfile cuureport.txt
     EPOCHTIME=`date --rfc-3339=seconds |gawk '{print $1 "." $2}'`
     DSTAMP=`date '+%F%H%M%S' | sed 's/-//g'`
     FNAME="cuureport"-$EPOCHTIME".txt"
     print $FNAME
     cp cuureport.txt $FNAME
     aws --profile $ACCOUNT s3api put-object --bucket ecd3pub --key $FNAME --body $FNAME --content-type text/plain > $Tmp
     aws --profile $ACCOUNT s3 ls s3://ecd3pub --recursive
     java Gpurl us-east-1 ecd3pub $FNAME 15
fi

if [ "$COMMAND" == "TIME" ] ; then
     print "WINDOW START TIME  "$ISOAGO"  "$AGO
     print "WINDOW END TIME    "$ISOANON"  "$ANON
fi
if [ "$COMMAND" == "WWEC2" ] ; then
                    assert "$ACCOUNT"  "Profile not specified"
                    LIST=`aws ec2 describe-regions --query "Regions[*].RegionName" --output text`
                    for ITEM in $LIST; do
                    aws --profile $ACCOUNT  --region $ITEM ec2 describe-instances --query "Reservations[*].Instances[*].
                              {ST: State.Name, ID:InstanceId, TY: InstanceType}" --output text | gawk -v r=$ITEM '{print r,$0;}'
                    done

fi
if [ "$COMMAND" == "GETPOLICY" ] ; then
     assert "$ACCOUNT"  "Profile not specified"
     assert "$THING"    "Policy not specified"
     LIST=`aws --profile $ACCOUNT iam list-policies --scope All --output text --query "Policies[*].[join(',',[PolicyName,Arn,DefaultVersionId])]" |grep $THING |tee $Tmp`
     cat $Tmp
fi

if [ "$COMMAND" == "UPDATEPOLICY" ] ; then
               assert "$ACCOUNT"  "Profile not specified"
               assert "$THING"    "Policy not specified"
               asserte "$DOCUMENT" "Document not specified"
               THIS=`aws --profile $ACCOUNT sts get-caller-identity --output text --query "Account"`
               ARN="arn:aws:iam::"$THIS":policy/"$THING
               LIST=`aws --profile $ACCOUNT iam list-policy-versions --output text --policy-arn $ARN --query "Versions[*].[VersionId]" |gawk -f skipfirst.awk`
               for ITEM in $LIST; do
                    aws --profile $ACCOUNT iam delete-policy-version --policy-arn $ARN --version-id $ITEM
               done
               aws --profile $ACCOUNT iam create-policy-version  --policy-arn $ARN --policy-document $DOCUMENT --set-as-default
               aws --profile $ACCOUNT iam list-policy-versions --output text --policy-arn $ARN --query "Versions[*].[VersionId,CreateDate,IsDefaultVersion]" 
               THIS=""
               ARN=""
fi
if [ "$COMMAND" == "GETALLPOLICIES" ] ; then
               assert "$ACCOUNT"  "Profile not specified"
               if [ "$THING" == "" ] ; then
                    LIST=`aws --profile $ACCOUNT iam list-policies --scope All --output text --query "Policies[*].[join(',',[PolicyName,Arn,DefaultVersionId])]" | tee $Tmp`
               else 
                    LIST=`aws --profile $ACCOUNT iam list-policies --scope All --output text --query "Policies[*].[join(',',[PolicyName,Arn,DefaultVersionId])]" |egrep $THING |tee $Tmp`
               fi
               CT=`cat $Tmp | wc -l`
               confirmprompt $CT" Policy Document(s) will be retrieved"
               mkdir -p ./policies
               for ITEM in $LIST; do
                    gNAME=`print "$ITEM" | gawk -F, '{print $1}'`
                    gVER=`print "$ITEM" | gawk -F, '{print $3}'`
                    gFILE="./policies/"$ACCOUNT"___"$gNAME"___"$gVER
                    gARN=`print "$ITEM" | gawk -F, '{print $2}'`
                    gARNFILE=`print "$ITEM" | gawk -F, '{gsub(/[/]/,"::::",$2);print "./policies/"$2}'`
                    print "\nUpdate with:"
                    print "cuu -a "$ACCOUNT" -c updatepolicy  -t "$gARN"   -D file://"
                    print $gARNFILE
                    print "this.json"
                    aws --profile $ACCOUNT --output json iam get-policy-version --policy-arn $gARN --version-id $gVER | jq .[].Document.Statement > $gARNFILE
                    cp $gARNFILE this.json
               done
fi
if [ "$COMMAND" == "GETLOCALPOLICIES" ] ; then
               assert "$ACCOUNT"  "Profile not specified"
               if [ "$THING" == "" ] ; then
                    LIST=`aws --profile $ACCOUNT iam list-policies --scope Local --output text --query "Policies[*].[join(',',[PolicyName,Arn,DefaultVersionId])]" |tee $Tmp`
               else 
                    LIST=`aws --profile $ACCOUNT iam list-policies --scope Local --output text --query "Policies[*].[join(',',[PolicyName,Arn,DefaultVersionId])]" |egrep $THING |tee $Tmp`
               fi
               CT=`cat $Tmp | wc -l`
               confirmprompt $CT" Policy Document(s) will be retrieved"
               mkdir -p ./policies
               mkdir -p ./rawpolicies
               for ITEM in $LIST; do
                    gNAME=`print "$ITEM" | gawk -F, '{print $1}'`
                    gVER=`print "$ITEM" | gawk -F, '{print $3}'`
                    gARN=`print "$ITEM" | gawk -F, '{print $2}'`
                    gARNFILE=`print "$ITEM" | gawk -F, '{gsub(/[/]/,"::::",$2);print "policies/"$2}'`
                    print "\nUpdate with:"
                    print "cuu -a "$ACCOUNT" -c updatepolicy  -t "$gNAME"   -D file://"
                    print $gARNFILE
                    print "this.json"
                    aws --profile $ACCOUNT --output json iam get-policy-version --policy-arn $gARN --version-id $gVER  > $gARNFILE
                    cp $gARNFILE this.json
               done
fi
# ----------------------------------------------------
# Fundamental User Commands
#       Create User, Change Password, Delete User
# ----------------------------------------------------
if [ "$COMMAND" == "CREATEADMINUSER" ] ; then
               assertACCOUNTandUSERNAMEandPASSWORD
               createUSER
               policyATTACH arn:aws:iam::aws:policy/AdministratorAccess
               optionalGROUPADD
fi
if [ "$COMMAND" == "CREATEREADONLYUSER" ] ; then
               assertACCOUNTandUSERNAMEandPASSWORD
               createUSER
               policyATTACH arn:aws:iam::aws:policy/ReadOnlyAccess
               optionalGROUPADD
fi
if [ "$COMMAND" == "CREATEUSERNOKEY" ] ; then
               assertACCOUNTandUSERNAMEandPASSWORD
               createUSER
               optionalGROUPADD
fi
if [ "$COMMAND" == "CREATEUSER" ] ; then
               assertACCOUNTandUSERNAMEandPASSWORD
               createUSER
               optionalGROUPADD
               createACCESSKEY
fi
if [ "$COMMAND" == "CHANGEPASSWORD" ] ; then
               assertACCOUNTandUSERNAMEandPASSWORD
               confirm
               aws --profile $ACCOUNT iam update-login-profile --user-name $USERNAME --password $PASSWORD  --password-reset-required
fi
if [ "$COMMAND" == "SCRAMPASSWORD" ] ; then
               assertACCOUNTandUSERNAME
               RAN=`tr -cd \#_[:alnum:] < /dev/urandom |  fold -w 18 | head -1 |gawk '{print $0 "!!"}'`
               confirm
               aws --profile $ACCOUNT iam update-login-profile --user-name $USERNAME --password $RAN
fi
if [ "$COMMAND" == "DELETEUSER" ] ; then
               assertACCOUNTandUSERNAME
               wipeUSER
               deleteUSER
fi




if [ "$COMMAND" == "ACCOUNTNUMBER" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               aws --profile $ACCOUNT sts get-caller-identity --output text --query "Account"
fi
# ----------------------------------------------------
# These commands operate on accounts
# ----------------------------------------------------
if [ "$COMMAND" == "LISTROLES" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               clean
               for ITEM in $ACCOUNT; do
                    aws --profile $ITEM iam list-roles --query "Roles[*].[Arn]" >> $Tmp
               done
               cat $Tmp | gawk -v A=$ITEM -f noindent.awk | column -t
fi
if [ "$COMMAND" == "LISTUSERS" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               clean
               for ITEM in $ACCOUNT; do
                    aws --profile $ITEM iam list-users --query "Users[*].[UserName,CreateDate,Arn]" >> $Tmp
               done
               cat $Tmp | gawk -v A=$ITEM -f noindent.awk | column -t
fi
if [ "$COMMAND" == "USERMENU" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               buildUSERLIST  $ACCOUNT
               clean
               print "PS3='Pick user, enter choice:'" > $Tmp
               print -n "select clean_menu in " >> $Tmp
               for USER in $USERLIST; do
                    print -n "\""$USER"\" " >> $Tmp
               done
               print "\"Exit\"" >> $Tmp
               print "do" >> $Tmp
               print "case \$clean_menu in" >> $Tmp
               for USER in $USERLIST; do
                    print "\""$USER"\")" >> $Tmp
                    print "cuu -a ECD1 -c du -u "$USER";;" >> $Tmp
               done
               print "\"Exit\") break;;" >> $Tmp
               print "esac" >> $Tmp
               print "done" >> $Tmp
               chmod 777 $Tmp
               $Tmp
fi


if [ "$COMMAND" == "CREATEGROUP" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               assert "$THING"   "Group not specified"
               clean
               aws --profile $ACCOUNT iam create-group --group-name $THING --output text
               aws --profile $ACCOUNT iam list-groups --output text --query "Groups[*].[GroupName,CreateDate,Arn]"
fi
if [ "$COMMAND" == "DELETEGROUP" ] ; then
               assert "$USERNAME" "Username not specified"
               assert "$ACCOUNT" "Profile not specified"
               assert "$THING" "Group not specified"
               aws --profile $ACCOUNT iam delete-group --group-name $THING
fi
if [ "$COMMAND" == "LISTGROUPS" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               clean
               for ITEM in $ACCOUNT; do
                    aws --profile $ITEM iam list-groups --output text --query "Groups[*].[GroupName,CreateDate,Arn]" >> $Tmp
               done
               cat $Tmp | gawk -v A=$ITEM -f noindent.awk | column -t
fi
if [ "$COMMAND" == "LISTALLPOLICIES" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               clean
               for ITEM in $ACCOUNT; do
                    aws --profile $ITEM --output text iam list-policies --scope All --query "Policies[*].[Arn]" | sort
               done
fi
if [ "$COMMAND" == "LISTLOCALPOLICIES" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               clean
               for ITEM in $ACCOUNT; do
                   aws --profile $ITEM --output text iam list-policies --scope Local --query "Policies[*].[PolicyName,UpdateDate,DefaultVersionId,Arn]" | column -t
               done
fi
if [ "$COMMAND" == "LISTAWSPOLICIES" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               clean
               for ITEM in $ACCOUNT; do
                    aws --profile $ITEM --output text iam list-policies --scope AWS --query "Policies[*].[PolicyName,UpdateDate,DefaultVersionId,Arn]" | column -t
               done
fi

if [ "$COMMAND" == "ATTACHPOLICYSET" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               assert "$USER" "Profile not specified"
               policysetATTACH
fi
if [ "$COMMAND" == "REMOVEPOLICYSET" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               assert "$USER" "Profile not specified"
               policysetREMOVE
fi
if [ "$COMMAND" == "DESCRIBEUSERS" ] ; then
     assert "$ACCOUNT" "Profile not specified"
     clean
     for ITEM in $ACCOUNT; do
          buildUSERLIST $ITEM
          for USER in $USERLIST; do
           print $ITEM $USER |tee -a cuu.out
           GROUPLIST=`aws --profile $ITEM iam list-groups-for-user  --output text --user-name $USER --query "Groups[*].[GroupName]"`
           aws --profile $ITEM iam list-groups-for-user        --user-name $USER --query "Groups[*].{ARN:Arn}" |
                                   gawk -v A=$USER -v B=$ITEM -v C="GRP" -f indent.awk |tee -a cuu.out
           for G in $GROUPLIST; do
                aws --profile $ITEM iam list-attached-group-policies --group-name $G --query "AttachedPolicies[*].{ARN:PolicyArn}" |
                                        gawk -v A=$USER -v B=$ITEM -v C="GPO" -f indent.awk |tee -a cuu.out 
           done
           aws --profile $ITEM iam list-attached-user-policies --user-name $USER --query "AttachedPolicies[*].{ARN:PolicyArn}" |
                                   gawk -v A=$USER -v B=$ITEM -v C="UPO" -f indent.awk |tee -a cuu.out 
           aws --profile $ITEM iam list-access-keys            --user-name $USER --query "AccessKeyMetadata[*].[AccessKeyId]"  |
                                   gawk -v A=$USER -v B=$ITEM -v C="KEY" -f indent.awk |tee -a cuu.out

           done 
     done 
fi
# ----------------------------------------------------
# These commands operate on users
# ----------------------------------------------------
if [ "$COMMAND" == "LISTUSERPOLICIES" ] ; then
               assertACCOUNTandUSERNAME
               aws --profile $ACCOUNT iam list-attached-user-policies --user-name $USERNAME --query "AttachedPolicies[*].[PolicyName,PolicyArn]" --output text
fi
if [ "$COMMAND" == "LISTUSERGROUPS" ] ; then
               assertACCOUNTandUSERNAME
               aws --profile $ACCOUNT iam list-groups-for-user --user-name $USERNAME --query "Groups[*].[GroupName]" --output text
fi
if [ "$COMMAND" == "REMOVEUSERFROMALLGROUPS" ] ; then
    wipeGROUPS
fi

if [ "$COMMAND" == "NEWPOLICYDOC" ] ; then
               cp policydoc.json this.json
fi
if [ "$COMMAND" == "CREATEPOLICY" ] ; then
               assertACCOUNTandTHING "Policy-Name"
               confirm
               aws --profile $ACCOUNT iam create-policy --policy-name $THING --policy-document file://this.json
               THIS=""
fi
if [ "$COMMAND" == "DELETEPOLICY" ] ; then
               assertACCOUNTandTHING "Policy-Name"
               confirm
               THIS=`aws --profile $ACCOUNT sts get-caller-identity --output text --query "Account"`
               aws --profile $ACCOUNT iam delete-policy --policy-arn "arn:aws:iam::"$THIS":policy/"$THING
               THIS=""
fi

if [ "$COMMAND" == "DETACHUSERPOLICIES" ] ; then
               assertACCOUNTandUSERNAME
               confirm
               aws --profile $ACCOUNT iam list-attached-user-policies --user-name $USERNAME | gawk -v A=$ACCOUNT -v U=$USERNAME '
               {
                   sz = "aws --profile " A " iam detach-user-policy --user-name " U " --policy-arn " $2
                   system(sz)
               }'
fi
if [ "$COMMAND" == "ATTACHPOLICYTOALLUSERS" ] ; then
               assertACCOUNTandTHING "Policy-ARN"
               buildUSERLIST $ACCOUNT
               for USER in $USERLIST; do
                    policyATTACH $THING
               done
               USERLIST=""
fi
if [ "$COMMAND" == "ATTACHPOLICYTOUSER" ] ; then
               assertACCOUNTandUSERNAME
               assert "$THING" "Thing not specified"
               policyATTACH $THING
fi


if [ "$COMMAND" == "IAMNAMEDPOLICY-REMOVE" ] ; then
               assertACCOUNTandUSERNAMEandTHING "Policy-ARN"
               policyREMOVE $THING
fi
if [ "$COMMAND" == "IAMNAMEDPOLICY-ADD" ] ; then
               assertACCOUNTandUSERNAMEandTHING "Policy-ARN"
               policyATTACH $THING
fi
if [ "$COMMAND" == "IAMNAMEDPOLICY-REMOVE" ] ; then
               assertACCOUNTandTHING "Policy-Name"
               THIS=`aws --profile $ACCOUNT sts get-caller-identity --output text --query "Account"`
               policyREMOVE "arn:aws:iam::"$THIS":policy/"$THING
               THIS=""
fi
if [ "$COMMAND" == "IAMNAMEDPOLICY-ADD" ] ; then
               assertACCOUNTandTHING "Policy-Name"
               THIS=`aws --profile $ACCOUNT sts get-caller-identity --output text --query "Account"`
               policyATTACH "arn:aws:iam::"$THIS":policy/"$THING
               THIS=""
fi

if [ "$COMMAND" == "IAMUSERCODECOMMITPOWERUSER-ADD" ] ; then
               assertACCOUNTandUSERNAME
               policyATTACH "arn:aws:iam::aws:policy/AWSCodeCommitPowerUser"
fi
if [ "$COMMAND" == "IAMUSERCHANGEPASSWORD-ADD" ] ; then
               assertACCOUNTandUSERNAME
               policyATTACH "arn:aws:iam::aws:policy/IAMUserChangePassword"
fi
if [ "$COMMAND" == "IAMUSERCHANGEPASSWORD-REMOVE" ] ; then
               assertACCOUNTandUSERNAME
               policyREMOVE arn:aws:iam::aws:policy/IAMUserChangePassword
fi

if [ "$COMMAND" == "LISTUSERSINGROUP" ] ; then
     assertACCOUNTandTHING "Group-Name"
     USERLIST=`aws --profile $ACCOUNT iam get-group --output text --group-name $THING --query "Users[*].[UserName]"`
     for USER in $USERLIST; do
         print $USER
     done
     USERLIST=""
fi
if [ "$COMMAND" == "ADDUSERTOGROUP" ] ; then
     assertACCOUNTandTHING "Group-Name"
     aws --profile $ACCOUNT iam add-user-to-group --group-name $THING  --user-name $USERNAME
     aws --profile $ACCOUNT iam list-groups-for-user --user-name $USERNAME --query "Groups[*].{ARN:Arn}" |
                                gawk -v A=$USER -v B=$ACCOUNT -v C="GRP" -f noindent.awk
fi

if [ "$COMMAND" == "SWAP" ] ; then
               assertACCOUNTandUSERNAME
               policyATTACH $POLICYADD
               groupREMOVE $GROUPREMOVE
fi
if [ "$COMMAND" == "REMOVEUSERFROMGROUP" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               assert "$USERNAME" "Username not specified"
               assert "$THING" "Group not specified"
               confirm
               aws --profile $ACCOUNT iam remove-user-from-group --user-name $USERNAME --group-name $THING 
fi

if [ "$COMMAND" == "CLOUDTRAIL-ACTIVE" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               aws --profile $ACCOUNT --output text cloudtrail lookup-events --start-time $ISOAGO | gawk '
               /^EVENTS/ {
                    print $NF 
               }' | sort | uniq
fi

if [ "$COMMAND" == "REPLACEACCESSKEYS" ] ; then
               assertACCOUNTandUSERNAME
               confirm
               wipeACCESSKEYS
               aws --profile $ACCOUNT --output text iam create-access-key --user-name $USERNAME > $Tmp
               aws --profile $ACCOUNT --output text iam list-access-keys --user-name $USERNAME
               cat $Tmp | gawk -v A=$ACCOUNT -v U=$USERNAME ' @include "cuu.awk"; {print configrecord($0,A,U,A);}'
fi
if [ "$COMMAND" == "CREATEACCESSKEY" ] ; then
               assertACCOUNTandUSERNAME
               aws --profile $ACCOUNT --output text iam create-access-key --user-name $USERNAME > $Tmp
               aws --profile $ACCOUNT --output text iam list-access-keys --user-name $USERNAME
               cat $Tmp | gawk -v A=$ACCOUNT -v U=$USERNAME ' @include "cuu.awk"; {print configrecord($0,A,U);}'
fi
if [ "$COMMAND" == "LISTACCESSKEYS" ] ; then
               assertACCOUNTandUSERNAME
               aws --profile $ACCOUNT --output text iam list-access-keys --user-name $USERNAME
fi
if [ "$COMMAND" == "DELETEACCESSKEYS" ] ; then
               assertACCOUNTandUSERNAME
               confirm
               wipeACCESSKEYS
fi

if [ "$COMMAND" == "EC2" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               aws --profile $ACCOUNT --output text ec2 describe-instances | gawk 'BEGIN {print "\n\n\n"}/INSTANCES/{print $0}/SECURITYGROUPS/{print $0 "\n\n\n"}'
fi

if [ "$COMMAND" == "EC2-LIST" ] ; then
     assert "$ACCOUNT" "Profile not specified"
     for ACCT in $ACCOUNT; do
          LIST="us-east-1 us-east-2 us-west-1 us-west-2"
          for ITEM in $LIST; do
               aws --profile $ACCT ec2 describe-instances --output text --region $ITEM \
                   --query "Reservations[*].Instances[*].[InstanceId,InstanceType,State.Name,Tags[?Key==Name].Value]" | gawk -v A=$ACCT -v B=$ITEM -f noindent.awk
          done
      done
fi

#          XLIST=`aws --profile $ACCOUNT ec2 describe-regions --query "Regions[*].RegionName" --output text`



if [ "$COMMAND" == "EC2-SGSUM" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               aws --output text --profile $ACCOUNT ec2 describe-security-groups --query '
                               SecurityGroups[*].{
                                    SG:GroupId,
                                    PERM:IpPermissions[*].
                                         {PR:IpProtocol,
                                          FP:FromPort,
                                          TP:ToPort,
                                          IP:IpRanges[*].CidrIp,
                                          UG:UserIdGroupPairs[*].{GI:GroupId}
                                         }
                               }' |  gawk -F " " -v A=$ACCOUNT '
               BEGIN    {szOut="";}
               /^sg[-]/ {print szOut;szOut=$1;}
               /^PERM/ { szOut=szOut " " $3; }
           ' 
fi
if [ "$COMMAND" == "EC2-SG" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               aws --output text --profile $ACCOUNT ec2 describe-security-groups --query '
                               SecurityGroups[*].{
                                    SG:GroupId,
                                    PERM:IpPermissions[*].
                                         {PR:IpProtocol,
                                          FP:FromPort,
                                          TP:ToPort,
                                          IP:IpRanges[*].CidrIp,
                                          UG:UserIdGroupPairs[*].{GI:GroupId}
                                         }
                               }' |  gawk -F " " -v A=$ACCOUNT '
               BEGIN    {FLAG=0;ct=6;}
               /^sg[-]/ {SG=$1;ct=6;}
               /^PERM/ {
                    proto=$3; sub(/[-]1/,"all",proto);if (match(proto,/all/)>0) FLAG=1; 
                    fport=$2; sub(/None/,"all",fport);if (match(fport,/all/)>0) FLAG=1; 
                    fport=$2; sub(/[-]1/,"all",fport);if (match(fport,/all/)>0) FLAG=1; 
                    tport=$4; sub(/None/,"all",tport);if (match(tport,/all/)>0) FLAG=1; 
                    tport=$4; sub(/[-]1/,"all",tport);if (match(tport,/all/)>0) FLAG=1; 
                    printf("\n%4s %-20s %-5s %6s %6s",A,SG,proto,fport,tport)
                    block="                                                   ";
                    ctl="\n";
               }
               /^UG/ { printf(" %28s",$2)}
               /^IP/ {     
                          if (match($2,/0[.]0[.]0[.]0/) > 0 ) FLAG=1; 
                          if (( ct % 5) == 0) printf("\n                                             ");
                          printf(" %28s",$2); ct++;
                     }
               END   { printf("\n"); if (FLAG==1) printf("\n*** FLAGGED SUSPECT IPs/SGs/Protos ***\n");}
           ' 
fi
if [ "$COMMAND" == "EC2-SPARK" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               aws --profile $ACCOUNT --output text ec2 describe-instances | gawk 'BEGIN {}/INSTANCES/{if(NF==19) print $8;if(NF==22) print $9}' | gawk -v S=$ISOAGO -v A=$ACCOUNT '
               @include "cuu.awk"
               {
               sz ="aws --profile " A " cloudwatch get-metric-statistics --metric-name CPUUtilization --period 3600 --namespace AWS/EC2 --statistics Maximum \
                   --dimensions Name=InstanceId,Value=" $0 " --start-time " isoyesterday(1) " --end-time " isonow()
               print "INSTANCE " $0
               system(sz)
           } ' | gawk '
           @include "cuu.awk" 
           BEGIN {ct=1;fc=0;file="file0"}
           END {print ""}
           /XXINSTANCE/ {printf("\n./spark ",$1)}
           /INSTANCE/ {close(file);fc++;file="file" fc}
           /INSTANCE/ {printf("%s\n",$0)}
           /DATAPOINTS/ {ct++;printf("%5.2f\n", $2) >> file}
           ' 
           fi

if [ "$COMMAND" == "EC2-UTIL" ] ; then
               assert "$ACCOUNT" "Profile not specified"
               aws --profile $ACCOUNT --output text ec2 describe-instances | gawk 'BEGIN {}/INSTANCES/{if(NF==19) print $8;if(NF==22) print $9}' | gawk -v S=$ISOAGO -v A=$ACCOUNT '
               @include "cuu.awk"
               {
               sz ="aws --profile " A " cloudwatch get-metric-statistics --metric-name CPUUtilization --period 300 --namespace AWS/EC2 --statistics Maximum \
                   --dimensions Name=InstanceId,Value=" $0 " --start-time " isoyesterday(1) " --end-time " isonow()
               print "INSTANCE " $0
               system(sz)
           } ' | gawk '
           @include "cuu.awk" 
           /INSTANCE/ {printf("%s\n",$0)}
           /DATAPOINTS/ {printf("METRIC %5.2f %s\n", $2, isotolocal($3))}
           ' 
           fi


# aws --profile  ce get-cost-and-usage --granularity MONTHLY --metrics BlendedCost --time-period Start=2018-04-01,End=2018-04-30  


if [ "$COMMAND" == "CLOUDTRAIL-WATCH" ] ; then
               assert "PROFILELIST"  "Profile  not specified"
               if [ "$USERNAME" == "" ] ; then
                    assert "$WATCHUSER"    "User not specified"
                    for sz in $PROFILELIST; do
                         cuu -a $sz -c CU -u $WATCHUSER $DETAILFLAG
                    done
               else
                    assert "$USERNAME"    "User not specified"
                    for sz in $PROFILELIST; do
                         cuu -a $sz -c CU -u $USERNAME $DETAILFLAG
                    done
               fi
fi
if [ "$COMMAND" == "CLOUDTRAIL-USER" ] ; then
               assert "$ACCOUNT"  "Profile not specified"
               assert "$USERNAME" "Username not specified"
               clean
               window | tee -a cuureport.txt
               if [ "$USERNAME" == "ALL" ] ; then
                 aws --profile $ACCOUNT --region $REGION --output text cloudtrail lookup-events --no-paginate --start-time $ISOAGO  > $Tmp
               else
                 aws --profile $ACCOUNT --region $REGION --output text cloudtrail lookup-events --no-paginate --start-time $ISOAGO --lookup-attributes AttributeKey=Username,AttributeValue=$USERNAME > $Tmp
               fi
               cat $Tmp | gawk  -v USR=$USERNAME -v ACCT=$ACCOUNT -v DETAIL=$DETAIL -v BN=$BIGNAMES -v BE=$BIGEVENTS -v RAW=$SHOWRAW -v ISOTIME=$ISOTIME '
               @include "cuu.awk"
               /^EVENTS/ {
                    sz=$0;
                    timepre=jget($0, "^.*[\"]eventTime[\"]:","NA");
                    ip=  jget($0, "^.*[\"]sourceIPAddress[\"]:","NA");
                    ty=  jget($0, "^.*[\"]eventType[\"]:","NA");
                    en=  jget($0, "^.*[\"]eventName[\"]:","NA");
                    req= jget($0, "^.*[\"]requestParameters[\"]:","NA");
                    resp= jget($0, "^.*[\"]responseElements[\"]:","NA");
                    time=isotolocal(timepre, "%m/%d/%Y %I:%M:%S%p");
                    shorttime=isotolocal(timepre, "%m/%d/%Y");
                    if (match(ISOTIME,/^yes/) > 0 ) {
                         time=timepre;
                         shorttime=timepre;
                    }
                    name=$NF;
                    sub(/HIDDEN_DUE_TO_SECURITY_REASONS/,"HIDDEN",name);
                    if (match(DETAIL,/^yes/) == 0) {
                         sub(/^Aws/, "", ty);
                         gsub(/["]/, "", resp);
                         gsub(/Validation/, "Valid", resp);
                         gsub(/Region/, "Reg", resp);
                         gsub(/Required/, "Req", resp);
                         gsub(/Bucket/, "Bk", resp);
                         gsub(/Service/, "Sv", resp);
                         gsub(/[ ]/, "", resp);
                         gsub(/createDate/, "cD", resp);
                         gsub(/userName/, "uN", resp);
                         gsub(/userName/, "uN", req);
                         gsub(/userId/, "uID", resp);
                         gsub(/AIDA................/, "AIDA..", resp);
                         gsub(/Jan/,"01",resp); gsub(/Feb/,"02",resp); gsub(/Mar/,"03",resp); gsub(/Apr/,"04",resp); gsub(/May/,"05",resp); gsub(/Jun/,"06",resp);
                         gsub(/Jul/,"07",resp); gsub(/Aug/,"08",resp); gsub(/Sep/,"09",resp); gsub(/Oct/,"10",resp); gsub(/Nov/,"11",resp); gsub(/Dec/,"12",resp);
                         gsub(/,2018/,"2018",resp);
                         gsub(/GroupName/,"GName",req);
                         gsub(/StreamName/,"SName",req);
                         gsub(/GroupName/,"GName",resp);
                         gsub(/StreamName/,"SName",resp);
                         gsub(/Permission/,"Perm",resp);
                         gsub(/Protocol/,"Prtcl",resp);
                         gsub(/Permission/,"Perm",req);
                         gsub(/Protocol/,"Prtcl",req);
                         gsub(/Port/,"P",req);
                         gsub(/request/,"req",req);
                         gsub(/request/,"req",resp);
                         gsub(/vpcConfig/,"vpcCfg",req);
                         gsub(/vpcConfig/,"vpcCfg",resp);
                         gsub(/memorySize/,"memSz",req);
                         gsub(/memorySize/,"memSz",resp);
                         gsub(/revisionId/,"revId",req);
                         gsub(/revisionId/,"revId",resp);
                         gsub(/destinationCidrBlock/,"DestCidr",req);
                         gsub(/destinationCidrBlock/,"DestCidr",resp);

                         gsub(/[Bb]lock/,"Bblk",req);
                         gsub(/[Bb]lock/,"Bblk",resp);

                         gsub(/[Pp]rivate/,"Prv",req);
                         gsub(/[Pp]rivate/,"Prv",resp);
                         gsub(/[Pp]ublic/,"Pub",req);
                         gsub(/[Pp]ublic/,"Pub",resp);
                         gsub(/[Aa]llocation/,"Alloc",req);
                         gsub(/[Aa]llocation/,"Alloc",resp);
                         gsub(/[Aa]llocate/,"Alloc",req);
                         gsub(/[Aa]llocate/,"Alloc",resp);
                         gsub(/[Aa]llocate/,"Alloc",ty);
                         
                         
                         
                         
                         gsub(/[Aa]ssociation/,"Assoc",req);
                         gsub(/[Aa]ssociation/,"Assoc",resp);
                         gsub(/[Aa]ssociation/,"Assoc",ty);
                         gsub(/[Aa]ssociate/,"Assoc",req);
                         gsub(/[Aa]ssociate/,"Assoc",resp);
                         gsub(/[Aa]ssociate/,"Assoc",ty);

                         gsub(/[Mm]odify/,"Mod",ty);
                         gsub(/[Ii]nstance/,"Inst",ty);
                         gsub(/[Ss]ecurity/,"Sec",ty);
                         gsub(/[Aa]uthorize/,"Auth",ty);
                         gsub(/[Aa]ttach/,"Atch",ty);
                         gsub(/[Gg]roup/,"Grp",ty);

                         gsub(/[Rr]oute/,"Rte",req);
                         gsub(/[Rr]oute/,"Rte",resp);
                         gsub(/[Rr]oute/,"Rte",ty);
                         gsub(/[Gg]ateway/,"Gtwy",req);
                         gsub(/[Gg]ateway/,"Gtwy",resp);
                         gsub(/[Gg]ateway/,"Gtwy",ty);

                         gsub(/keyFingerprint:..:..:..:..:..:..:..:..:..:..:..:..:..:../,"keyFngPrnt..",req);
                         gsub(/keyFingerprint:..:..:..:..:..:..:..:..:..:..:..:..:..:../,"keyFngPrnt..",resp);
                         gsub(/AKIA........./,"AKIA..",req);
                         gsub(/AKIA........./,"AKIA..",resp);
                         gsub(/........-....-....-....-............/,"...",req);
                         gsub(/........-....-....-....-............/,"...",resp);
                         gsub(/[Cc]onsole/,"Con",ty);
                         gsub(/[Cc]onsole/,"Con",resp);
                         gsub(/[Cc]onsole/,"Con",req);
                         gsub(/[Ss]ecurity/,"Sec",resp);

                         gsub(/[Ss]ecurity/,"Sec",req);
                         gsub(/functionName/,"fName",resp);
                         gsub(/functionName/,"fName",req);

                         gsub(/instance/,"inst",req);
                         gsub(/instance/,"inst",resp);
                         gsub(/group/,"grp",req);
                         gsub(/group/,"grp",resp);
                         gsub(/Profile/,"Prf",req);
                         gsub(/Profile/,"Prf",resp);
                         gsub(/[Nn]etwork/,"net",req);
                         gsub(/[Nn]etwork/,"net",resp);
                         gsub(/[Ii]nterface/,"inter",req);
                         gsub(/[Ii]nterface/,"inter",resp);
                         if (match(BE,/no/) > 0) {
                             gsub(/Configuration/,"Config",en);
                             gsub(/Config/,"Cfg",en);
                             gsub(/[Dd]elete/,"Del",en);
                             gsub(/[Ll]aunch/,"Lnch",en);
                             gsub(/[Cc]hange/,"Chg",en);
                             gsub(/[Ss]caling/,"Scl",en);
                             gsub(/Permission/,"Perm",en);
                             gsub(/Function/,"Func",en);
                             gsub(/Resource/,"Res",en);
                             gsub(/Update/,"Upd",en);
                             gsub(/Create/,"Cr",en);
                             gsub(/[Cc]onsole/,"Con",en);
                             gsub(/[Ii]nstance/,"Inst",en);
                             gsub(/[Aa]ssociation/,"Assoc",en);
                             gsub(/[Mm]odify/,"Mod",en);
                             gsub(/[Aa]ssociate/,"Assoc",en);
                             gsub(/[Gg]roup/,"Grp",en);
                             gsub(/[Aa]uthorize/,"Auth",en);
                             gsub(/[Gg]ateway/,"Gtwy",en);
                             gsub(/[Aa]ttach/,"Atch",en);
                             gsub(/[Aa]llocate/,"Alloc",en);
                             gsub(/[Ss]ecurity/,"Sec",en);
                             gsub(/[Rr]oute/,"Rte",en);
                             gsub(/[aeiou]/,"",en);
                             en=cutpad(en,12);
                         }
                         else {
                             en=cutpad(en,18);
                         }

                         if (match(BN,/no/) > 0) {
                             name=cutpad(name,10);
                         }

                         ty=cutpad(ty,8);

                         sub(/arn:aws:iam::......../,"arn:aws:iam::",req);
                         sub(/arn:aws:iam::......../,"arn:aws:iam::",resp);

                    }
                    else {

                         ty=cutpad(ty,18);
                    }
                    if (length(req) > 256) req=substr(req,1,256) "(TRUNCATED)";
                    if (length(resp) > 256) resp=substr(resp,1,256) "(TRUNCATED)";
                    # print "-"
                    # print "acct","time","name","eventtype","eventname","req","resp"
                    print trim(ACCT), time, name, ty, en, "IN-" req
                    print trim(ACCT), time, name, ty, en, "OU-" resp
                    if (match(RAW,/^yes/) != 0) print $0 "\n\n"
               }'  | sort -k 4,4 -k 3,3 | tee -a cuureport.txt
fi

if [ "$LOOP" == "yes" ] ; then
     if [ "$COMMAND" == "EXIT" ] ; then
                    exit 0
     fi
     if [ "$COMMAND" == "QUIT" ] ; then
                    exit 0
     fi
     if [ "$COMMAND" == "Q" ] ; then
                    exit 0
     fi
     if [ "$COMMAND" == "h" ] ; then
                    usage
     fi
     if [ "$COMMAND" == "H" ] ; then
                    usage
     fi
else
     exit 0
fi

print -n "cuu "$ACCOUNT" "$USERNAME" "$THING">> "
read COMMAND
     set -A array $COMMAND
     if [ "${array[0]}" == "ACCOUNT" ] ; then
          ACCOUNT="${array[1]}"
     fi
     if [ "${array[0]}" == "USERNAME" ] ; then
         USERNAME="${array[1]}"
     fi
     if [ "${array[0]}" == "THING" ] ; then
         THING="${array[1]}"
     fi
done

exit 1
