#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1

LOCAL=""
while getopts "l" arg
do
	case $arg in
            l) LOCAL="yes" ;;
        esac
done
ANON=`date`
print $ANON
cuu -c utilcommands | grep -v alias  > $Tmp


print "# CUU Repo - A set of AWS CLI Wrappers and Utility Scripts" > README.md
print "Script | Description | Usage | Defaults" >> README.md
print "------ | ----------- | ----- | --------" >> README.md
print "cuu | A multi function AWS CLI Wrapper Utility | See below" >> README.md
print "ec2ls | A ec2 listing utility | ec2ls -a \"\<profile list\>\" -r \"\<region list\>\" | All US regions" >> README.md
print "ec2sg | A sg check utility | ec2sg -a \"\<profile list\>\" -r \"\<region list\>\" | EUROPE, US, GLOBAL, or specific region string" >> README.md
print ""
printf "%s | %s | %s | %s | %s\n" "Command" "Options" "Ver" "Description" "Aliases" >> README.md
print "------------|----------------|--------------|-----------|-----------------" >> README.md 
cuu -c commands  >> README.md
print ""
print "### Examples" >> README.md
echo "<pre>" >> README.md
print " cuu -a ENV1 -c USERLIST" >> README.md
print " ec2ls -a \"ENV1 EVN2\""  >> README.md
echo "</pre>" >> README.md
echo " " >> README.md

print "## CUU - An AWS CLI Wrapper" >> README.md
print "###### Setup:  CUUHOME enviroment variable should be set to the cuu install directory" >> README.md
echo "<pre>" >> README.md
gawk -v ANON="$ANON" -f awk/readme.awk cuu  >> README.md
gawk -v ANON="$ANON" -f awk/readme.awk cuu  >  cuuhelp.txt
echo "</pre>" >> README.md


echo "### Commands  " >> README.md
echo "<pre>" >> README.md
cuu -c commands | sed -e "s/^[ ]*//" >> README.md
echo "</pre>" >> README.md


echo "### ~/.cuu.txt can contain defaults for these settings" >> README.md
echo "<pre>" >> README.md
cat .cuu.txt >> README.md
echo "</pre>" >> README.md
# cuu -c commandlist | sort | gawk '{printf "%s ", $0;if ((NR%4)==0) print "";}' | column -t >> README.md
# cuu -c commands | sort  >> README.md


echo "### Build Date" >> README.md
echo "<pre>" >> README.md
date >> README.md
echo "</pre>" >> README.md


egrep -v "^[<]" README.md >> cuuhelp.txt

git add README.md 
git add tabber.awk
git add awk/readme.awk
git add awk/skipfirst.awk
git add awk/isotolocal.awk
git add awk/indent.awk
git add awk/noindent.awk
git add awk/trim.awk
git add awk/cuu.awk
git add pushit
git add spark
git add cuu

git commit -m "Update"

if [ "$LOCAL" == "" ] ; then
     git push -u origin master
fi

