#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1


# gawk -f readme.awk cuu  > README.md

cuu -c utilcommands | grep -v alias  > $Tmp

echo "<pre>" > README.md

cat usage.txt >> README.md
echo "cuu commands" >> README.md
echo "  " >> README.md

echo "User Commands  " >> README.md
cat $Tmp | egrep "^[ ]*user" >> README.md
echo "  " >> README.md

echo "Password Commands  " >> README.md
cat $Tmp | egrep "^[ ]*password" >> README.md
echo "  " >> README.md

echo "AccessKey Commands  " >> README.md
cat $Tmp | egrep "^[ ]*accesskey" >> README.md
echo "  " >> README.md



echo "Policy Commands  " >> README.md
cat $Tmp | egrep "^[ ]*policy" >> README.md
echo "  " >> README.md
echo "Group Commands  " >> README.md
cat $Tmp | egrep "^[ ]*group" >> README.md
echo "  " >> README.md
echo "Role Commands  " >> README.md
cat $Tmp | egrep "^[ ]*role" >> README.md
echo "  " >> README.md


echo "VPC Commands  " >> README.md
cat $Tmp | egrep "^[ ]*vpc" >> README.md

echo "  " >> README.md
echo "EC2 Commands  " >> README.md
cat $Tmp | egrep "^[ ]*ec2" >> README.md

echo "  " >> README.md
echo "CloudTrail Commands  " >> README.md
cat $Tmp | egrep "^[ ]*cloudtrail" >> README.md

echo "  " >> README.md
echo "Utility Commands  " >> README.md
cat $Tmp | egrep "^[ ]*util" >> README.md


echo "  " >> README.md
echo "</pre>" >> README.md


echo "<pre>" >> README.md
echo "~/.cuu.txt  can contain defaults for these settings" >> README.md
cat .cuu.txt >> README.md
echo "</pre>" >> README.md
# cuu -c commandlist | sort | gawk '{printf "%s ", $0;if ((NR%4)==0) print "";}' | column -t >> README.md
# cuu -c commands | sort  >> README.md



echo "<pre>" >> README.md
echo "  " >> README.md
date >> README.md
echo "</pre>" >> README.md


git add readme.awk
git add README.md 
git add indent.awk
git add noindent.awk
git add cuu.awk
git add trim.awk
git add pushit
git add spark
git add cuu

git commit -m "Update"
git push -u origin master

